# Generated by Django 4.2.2 on 2023-06-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.DeleteModel(
            name='docs_types',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
